# Generated by Django 5.1.5 on 2025-01-26 17:56

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category name.', max_length=200, unique=True)),
                ('icon', models.CharField(default='', help_text='Enter an icon name.', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_case_insensitive_unique', violation_error_message='A category with this name already exists.')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a description of the project here.', max_length=5000)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_added', models.DateField(blank=True, null=True, verbose_name='date of creation')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.category')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='', help_text='Enter an icon name.', max_length=100)),
                ('address', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.project')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a technology name.', max_length=200, unique=True)),
                ('icon', models.CharField(default='', help_text='Enter an icon name.', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='technology_name_case_insensitive_unique', violation_error_message='A technology with this name already exists.')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(help_text='Select technologies used in this project.', to='catalog.technology'),
        ),
    ]
